SecondaryProject/src/webapp/MVC/SP.Webapp.MVC/Controllers/IdentidadeController.cs
using SP.Webapp.MVC.Services;
using Microsoft.AspNetCore.Mvc;
using SP.Webapp.MVC.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.IdentityModel.Tokens.Jwt;

namespace SP.Webapp.MVC.Controllers
{
    public class IdentidadeController : MainController
    {

        private readonly IAuthenticationServiceCustom _authenticationService;

        public IdentidadeController(IAuthenticationServiceCustom authenticationService)
        {
            _authenticationService = authenticationService;
        }

        [HttpGet]
        [Route("Registro")]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [Route("Registro")]
        public async Task<IActionResult> Registro(UsuarioRegistro UR)
        {
            if (!ModelState.IsValid) return View(UR);

            var Response = await _authenticationService.Registro(UR);
             
            if (ResponseHasErrors(Response.ResponseResult)) return View(UR);
            
            await RealizarLogin(Response);

            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Route("Login")]
        public IActionResult Login(string? returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        [Route("Login")]
        public async Task<IActionResult> Login(UsuarioLogin UL, string? returnUrl = null)
        {
            ViewData["ReturnUrl"] = returnUrl;
            if (!ModelState.IsValid) return View(UL);

            var Response = await _authenticationService.Login(UL);

            if (ResponseHasErrors(Response.ResponseResult)) return View(UL);

            await RealizarLogin(Response);

            if (string.IsNullOrEmpty(returnUrl)) return RedirectToAction("Index", "Home");

            return LocalRedirect(returnUrl);
        }

        [HttpGet]
        [Route("Logout")]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Login");
        }

        private async Task RealizarLogin(UsuarioResponseLogin responseLogin)
        {
            var token = GetFormatedToken(responseLogin.AccessToken);

            var claims = new List<Claim>();
            claims.Add(new Claim("JWT", responseLogin.AccessToken));
            claims.AddRange(token.Claims);

            var ClaimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties
            {
                ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(60),
                IsPersistent = true
            };
            
            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(ClaimsIdentity ),
                authProperties);
        }

        private static JwtSecurityToken GetFormatedToken(string token)
        {
            return new JwtSecurityTokenHandler().ReadToken(token) as JwtSecurityToken;
        }

    }
}

SecondaryProject/src/webapp/MVC/SP.Webapp.MVC/Extensions/SummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SP.Webapp.MVC.Extensions
{
    public class SummaryViewComponent : ViewComponent
    {
            
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }

    }

}

SecondaryProject/src/webapp/MVC/SP.Webapp.MVC/Views/Identidade/Login.cshtml
@model SP.Webapp.MVC.Models.UsuarioLogin

@{
    ViewData["Title"] = "Login de usuário";
}


<section class="section-conten padding-y container" style="min-height:35vh">
    
    <vc:summary></vc:summary>

    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">

        <div class="card-body">
            <h4>Seja bem vindo!</h4>
            <form asp-route-returnurl="@ViewData["ReturnUrl"]" method="post">

                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Entrar</button>
                </div>
            </form>
        </div>
        <div class="card-footer text-center">Ainda não tem uma conta?<a asp-controller="Identidade" asp-action="Registro"> Criar uma conta</a></div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

SecondaryProject/src/webapp/MVC/SP.Webapp.MVC/Views/Identidade/Registro.cshtml
@model SP.Webapp.MVC.Models.UsuarioRegistro

@{
    ViewData["Title"] = "Registro";
}

<h1>@ViewData["Title"]</h1>

<section class="section-conten padding-y container" style="min-height: 35vh">

    <vc:summary></vc:summary>
    <div class="card mx-auto" style="max-width: 380px; margin-top: 100px;">

        <div class="card-body">
            <h4>Registre-se e comece a comprar hoje mesmo !</h4>
            <hr />

            <form method="post">
                <div class="form-group">
                    <label asp-for="Email"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Senha"></label>
                    <input type="password" asp-for="Senha" class="form-control" />
                    <span asp-validation-for="Senha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SenhaConfirmacao"></label>
                    <input type="password" asp-for="SenhaConfirmacao" class="form-control" />
                    <span asp-validation-for="SenhaConfirmacao" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </form>

        </div>
        <div class="card-footer text-center">Já tem uma conta?<a asp-controller="Identidade" asp-action="Login"> Entrar</a></div>
    </div>
</section>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}